// Regenerates ui/icons.js from lucide-static (ISC). Run: node scripts/build-icons.mjs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
const names = ['house', 'message-circle', 'calendar', 'calendar-days', 'music', 'bell', 'bell-off', 'settings', 'puzzle', 'plus', 'x', 'grip-vertical', 'sliders-horizontal', 'play', 'pause', 'skip-back', 'skip-forward', 'shuffle', 'repeat', 'repeat-1', 'heart', 'volume-2', 'volume-x', 'map-pin', 'navigation', 'train-front', 'flask-conical', 'mail', 'sun', 'cloud', 'cloud-rain', 'cloud-snow', 'cloud-lightning', 'cloud-fog', 'cloud-sun', 'cloud-drizzle', 'moon', 'arrow-left', 'arrow-right', 'arrow-up', 'rotate-cw', 'minus', 'square', 'copy', 'trash-2', 'check', 'check-check', 'search', 'refresh-cw', 'external-link', 'chevron-left', 'chevron-right', 'chevron-down', 'chevron-up', 'layout-grid', 'image', 'palette', 'send', 'car', 'bike', 'footprints', 'clock', 'square-terminal', 'gauge', 'zap', 'flag', 'corner-up-left', 'corner-up-right', 'undo-2', 'arrow-up-left', 'arrow-up-right', 'rotate-ccw', 'eye', 'eye-off', 'notebook', 'globe', 'loader-circle', 'triangle-alert', 'inbox', 'hash', 'library', 'disc-3', 'maximize-2', 'minimize-2', 'locate-fixed', 'circle-check', 'pencil', 'log-in', 'list', 'panel-left', 'asterisk', 'at-sign', 'bot', 'split', 'git-merge', 'circle-dot', 'move-vertical', 'rows-3', 'type', 'link'];
const out = {};
for (const name of names) {
  const file = `node_modules/lucide-static/icons/${name}.svg`;
  if (!existsSync(file)) { console.warn('missing', name); continue; }
  out[name] = readFileSync(file, 'utf8').replace(/<!--[\s\S]*?-->/g, '').replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\s*\n\s*/g, '').trim();
}
writeFileSync('ui/icons.js', `// Generated by scripts/build-icons.mjs from lucide-static (ISC license).\nexport const ICONS = ${JSON.stringify(out, null, 0).replace(/","/g, '",\n  "').replace(/^\{/, '{\n  ').replace(/\}$/, '\n}')};\n`);
console.log(Object.keys(out).length, 'icons');
